<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/03 22:20:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=finansowa',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
