<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/06 22:41:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=finansowa',
  'username' => 'root',
  'password' => 'haslo',
  'name' => 'doctrine',
)),);
