StatusType:
  actAs:        { Timestampable: ~ }
  columns:
    name:       { type: string(255), notnull: true, unique: true }

Przedmioty:
  actAs:        { Timestampable: ~ }
  columns:
    name:       { type: string(255), notnull: true, unique: true }
    semestr:    { type: integer, notnull: false }
 
Users:
  actAs:        { Timestampable: ~ }
  columns:
    name:       { type: string(25), notnull: true, unique:true }
    pass:       { type: string(255), notnull: true }
    url:        { type: string(255), notnull: true }
    email:      { type: string(255), notnull: true, unique: true }
    type:       { type: integer, notnull: true}
    is_active:  { type: boolean, notnull: true, default: 0 }
  relations:
    StatusType: { onDelete: CASCADE, local: type, foreign: id, foreignAlias: Users } 

Pliki:
  columns:
    filename:   { type: string(255), notnull: true }
    przedmiot:  { type: integer, notnull: true }
    user:       { type: integer, notnull: true }
    komentarz:  { type: string(255), notnull:false }
    donwload:   { type: integer, notnull: true, default:0 }
  relations:
    Przedmioty: { onDelete: CASCADE, local: przedmiot, foreign: id }
    Users:      { onDelete: CASCADE, local: user, foreign: id }
